const privateEquityText = {
  Challenge:
    "Elit sequi molestiae numquam laboriosam eos? Ea dolorem quis minima ipsa minima? Asperiores saepe ipsum necessitatibus incidunt labore Obcaecati cupiditate rem quam nam quasi eaque aliquam voluptate enim. In a vitae aspernatur voluptates facilis? Ipsam eius eveniet odio doloribus cupiditate? Exercitationem placeat commodi labore obcaecati eveniet A dolorum saepe laborum voluptatem temporibus Atque at doloribus voluptate doloribus commodi. Veritatis blanditiis accusantium nihil architecto vero Laborum molestiae vero doloribus consequatur hic, ipsa. Ad quidem laborum assumenda maxime debitis nam. Error laborum repellendus laborum blanditiis velit repellendus? Repellendus nobis quis pariatur quis nulla aut modi? Amet reiciendis quaerat soluta minus exercitationem at!",
  Opportunity:
    "Adipisicing iure laboriosam delectus delectus eius dolor explicabo eaque. Voluptatum accusantium odio at praesentium assumenda. Ducimus blanditiis atque in voluptatum dolores Officiis sint sapiente optio soluta nisi. Eveniet sunt unde delectus distinctio deleniti voluptate, laborum saepe Debitis atque obcaecati amet blanditiis ipsa tenetur Esse veniam nemo facilis quam necessitatibus Accusantium tenetur vitae quisquam recusandae consectetur Pariatur fuga repudiandae molestias repellat nulla, cum blanditiis ad! Eveniet perspiciatis suscipit doloribus neque provident minus unde? A voluptatibus officia commodi dignissimos nihil Quaerat obcaecati dolor voluptates earum ipsam? Earum blanditiis quae provident consequatur repellendus, placeat. Temporibus obcaecati ab iste ratione at aut aperiam facilis!",
  Solution:
    "Lorem similique vitae consequatur modi vel. Distinctio magni quae dolorem nulla consequuntur! Quae ullam dolores qui dolorem sint pariatur Aperiam esse temporibus sed a enim illo voluptatibus! Obcaecati officiis aliquam saepe temporibus iusto voluptatem unde Eius ad harum nihil alias animi iusto Nemo necessitatibus sint magnam veniam officia voluptate? Incidunt sapiente incidunt at velit aut? Dolore necessitatibus sit optio ipsam ut Modi et dicta itaque consectetur nemo? Doloremque accusamus aperiam sit laudantium magni. Est dolorum perspiciatis minima sapiente cum? Optio deserunt facilis qui vitae sint Delectus natus quasi laudantium eaque inventore. Atque sed ipsa quia architecto consectetur Blanditiis iure quaerat",
  akilaAdvantage:
    "How Akila helps solve the problem.  Elit magni distinctio illum quod ratione Provident aliquid exercitationem maiores nostrum necessitatibus a Deleniti ut itaque recusandae cupiditate hic odit Impedit doloribus dolore eius exercitationem a! Enim nisi vel ipsa nulla sequi. Natus consequatur saepe eveniet ducimus quam Eligendi quam ipsa perferendis aut asperiores Totam quidem nihil amet ad sint beatae eius minima quibusdam? Voluptatem temporibus reiciendis maiores impedit repudiandae. Labore eos facilis nisi assumenda accusamus in! Dicta quaerat accusamus modi est qui, minus ipsa Explicabo nobis officiis maxime eum repellendus Vitae libero expedita magnam eveniet porro sit quam molestias corporis. Minima sint totam officiis obcaecati sunt. Consequatur iure provident",
};

export default privateEquityText;
